from __future__ import annotations


# 控制台與設定頁面共用同一份文字表，避免語言切換後出現中英混用。
TEXTS = {
    "zh": {
        "window_title": "CatDrop－後台控制台",
        "panel_title": "檔案接收控制台",
        "server_starting": "服務啟動中…",
        "server_running": "網站服務運作中 · TCP {port}",
        "server_failed": "網站服務啟動失敗",
        "connection_info": "連線資訊",
        "lan_url": "區網網址：{url}",
        "open_site": "開啟網站",
        "open_qr": "開啟 QR Code 資料夾",
        "generate_qr": "產生 QR Code",
        "copy_url": "複製網址",
        "lan_error_title": "無法產生區網網址",
        "lan_error": "自動修復失敗。\n\n錯誤碼：{code}\n原因：{detail}\n\n請確認電腦已連接私人網路、CatDrop 服務正在執行，並檢查 Windows 防火牆。",
        "qr_error_title": "QR Code 產生失敗",
        "qr_error": "無法寫入 QR Code。\n\n錯誤碼：{code}\n原因：{detail}",
        "qr_ready_title": "QR Code 已產生",
        "qr_ready": "已驗證區網網址並產生 QR Code：\n\n{path}",
        "copy_error_title": "網址複製失敗",
        "copy_error": "無法寫入剪貼簿。\n\n錯誤碼：{code}\n原因：{detail}",
        "copied_title": "網址已複製",
        "copied": "已複製：{url}",
        "settings": "設定",
        "accept_open": "接收中",
        "accept_paused": "已暫停",
        "notice_new": "有 {count} 個新檔案待處理",
        "notice_none": "目前沒有待處理的新檔案",
        "search": "搜尋",
        "date_all": "全部日期",
        "date_today": "今天",
        "date_7": "最近 7 天",
        "date_30": "最近 30 天",
        "export": "匯出紀錄",
        "delete": "刪除",
        "open_file": "開啟檔案",
        "mark_processed": "標記為已處理",
        "select_all": "全選",
        "column_status": "狀態",
        "column_source": "來源名稱",
        "column_name": "原始檔名",
        "column_stored": "儲存檔名",
        "column_size": "大小",
        "column_size_bytes": "大小(Byte)",
        "column_time": "上傳時間",
        "status_new": "新檔案",
        "status_processed": "已處理",
        "settings_title": "CatDrop 設定",
        "language": "介面語言",
        "chinese": "中文",
        "english": "English",
        "storage_path": "儲存路徑",
        "choose": "選擇",
        "max_file_mb": "單檔上限 MB",
        "startup": "登入 Windows 後自動啟動",
        "allowed_types": "支援的檔案類型",
        "allow_all_file_types": "全格式支援",
        "allow_all_warning": "啟用後將接受任何副檔名或無副檔名檔案，並略過檔案內容特徵驗證。只建議在可信任的私人網路使用。",
        "upload_state": "檔案上傳狀態",
        "upload_open": "開放接收",
        "upload_pause": "暫停接收",
        "show_toggle": "在控制台顯示接收狀態按鈕",
        "state_locked": "控制台按鈕啟用時，請由控制台切換接收狀態。",
        "save": "儲存",
        "cancel": "取消",
        "setting_error": "設定錯誤",
        "max_error": "單檔上限必須是 1 至 2048 的整數。",
        "storage_error": "無法建立儲存資料夾。\n\n{error}",
        "extension_error": "至少要勾選一種支援的檔案類型。",
        "saved_title": "設定完成",
        "saved": "設定已更新，網頁端會自動同步。",
        "server_error_title": "無法啟動網站",
        "server_error": "TCP {port} 可能已被占用，或缺少權限。\n\n{error}",
        "not_selected": "尚未選取",
        "select_to_process": "請先選取要處理的檔案紀錄。",
        "select_to_open": "請先選取要開啟的檔案紀錄。",
        "select_to_delete": "請先選取要刪除的檔案紀錄。",
        "confirm_delete_title": "確認刪除",
        "confirm_delete": "確定永久刪除選取的 {count} 個檔案與紀錄？此操作無法復原。",
        "delete_failed_title": "部分刪除失敗",
        "delete_failed": "以下檔案可能正被其他程式使用：\n{files}",
        "missing_title": "部分檔案無法開啟",
        "missing_files": "以下檔案已不存在或無法開啟：\n{files}",
        "choose_storage": "選擇檔案儲存資料夾",
        "export_title": "匯出上傳紀錄",
        "export_done_title": "匯出完成",
        "export_done": "上傳紀錄已匯出。",
        "startup_error_title": "設定失敗",
        "startup_error": "無法更新開機自動啟動設定。\n\n{error}",
    },
    "en": {
        "window_title": "CatDrop - Control Panel",
        "panel_title": "File Receiving Control Panel",
        "server_starting": "Starting service…",
        "server_running": "Web service running · TCP {port}",
        "server_failed": "Web service failed to start",
        "connection_info": "Connection",
        "lan_url": "LAN URL: {url}",
        "open_site": "Open website",
        "open_qr": "Open QR Code folder",
        "generate_qr": "Generate QR Code",
        "copy_url": "Copy URL",
        "lan_error_title": "LAN URL unavailable",
        "lan_error": "Automatic repair failed.\n\nError code: {code}\nReason: {detail}\n\nConfirm that this computer is connected to a private network, CatDrop is running, and Windows Firewall allows the service.",
        "qr_error_title": "QR Code generation failed",
        "qr_error": "The QR Code could not be written.\n\nError code: {code}\nReason: {detail}",
        "qr_ready_title": "QR Code ready",
        "qr_ready": "The LAN URL was verified and its QR Code was generated:\n\n{path}",
        "copy_error_title": "URL copy failed",
        "copy_error": "The clipboard could not be updated.\n\nError code: {code}\nReason: {detail}",
        "copied_title": "URL copied",
        "copied": "Copied: {url}",
        "settings": "Settings",
        "accept_open": "Receiving",
        "accept_paused": "Paused",
        "notice_new": "{count} new file(s) need attention",
        "notice_none": "No new files need attention",
        "search": "Search",
        "date_all": "All dates",
        "date_today": "Today",
        "date_7": "Last 7 days",
        "date_30": "Last 30 days",
        "export": "Export records",
        "delete": "Delete",
        "open_file": "Open files",
        "mark_processed": "Mark as processed",
        "select_all": "Select all",
        "column_status": "Status",
        "column_source": "Source",
        "column_name": "Original name",
        "column_stored": "Stored name",
        "column_size": "Size",
        "column_size_bytes": "Size (Byte)",
        "column_time": "Uploaded at",
        "status_new": "New",
        "status_processed": "Processed",
        "settings_title": "CatDrop Settings",
        "language": "Interface language",
        "chinese": "中文",
        "english": "English",
        "storage_path": "Storage path",
        "choose": "Choose",
        "max_file_mb": "File limit (MB)",
        "startup": "Start after signing in to Windows",
        "allowed_types": "Supported file types",
        "allow_all_file_types": "Allow all file types",
        "allow_all_warning": "When enabled, files with any extension or no extension are accepted without file-signature validation. Use only on a trusted private network.",
        "upload_state": "File upload status",
        "upload_open": "Accept uploads",
        "upload_pause": "Pause uploads",
        "show_toggle": "Show receiving status button on the control panel",
        "state_locked": "Use the control panel button while it is enabled.",
        "save": "Save",
        "cancel": "Cancel",
        "setting_error": "Settings error",
        "max_error": "The file limit must be an integer from 1 to 2048.",
        "storage_error": "The storage folder could not be created.\n\n{error}",
        "extension_error": "Select at least one supported file type.",
        "saved_title": "Settings saved",
        "saved": "Settings were updated. The web page will synchronize automatically.",
        "server_error_title": "Website failed to start",
        "server_error": "TCP {port} may be in use or unavailable.\n\n{error}",
        "not_selected": "Nothing selected",
        "select_to_process": "Select file records to process.",
        "select_to_open": "Select file records to open.",
        "select_to_delete": "Select file records to delete.",
        "confirm_delete_title": "Confirm deletion",
        "confirm_delete": "Permanently delete {count} selected file(s) and record(s)? This cannot be undone.",
        "delete_failed_title": "Some files could not be deleted",
        "delete_failed": "These files may be in use:\n{files}",
        "missing_title": "Some files could not be opened",
        "missing_files": "These files are missing or could not be opened:\n{files}",
        "choose_storage": "Choose the file storage folder",
        "export_title": "Export upload records",
        "export_done_title": "Export complete",
        "export_done": "Upload records were exported.",
        "startup_error_title": "Settings failed",
        "startup_error": "Windows startup could not be updated.\n\n{error}",
    },
}


def text(language: str, key: str, **values: object) -> str:
    """依語言取得介面文字，未知語言一律回退繁體中文。"""
    selected = language if language in TEXTS else "zh"
    return TEXTS[selected][key].format(**values)
